"""
Google Colab Fine-Tuning Pipeline for Plutus (Llama 3.1 8B) using Unsloth QLoRA
================================================================================
This script follows Section 3 of architecture.md.
Run this script or notebook inside Google Colab (T4 GPU instance).

Prerequisites:
  1. Mount Google Drive
  2. Upload `plutus_finetune_dataset.jsonl` (generated by dataset_prep.py)
"""

COLAB_UNSLOTH_SCRIPT = """
# 1. Install Unsloth and required packages in Colab
!pip install --no-deps "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers "trl<0.9.0" peft accelerate bitsandbytes

import torch
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# 2. Configuration & Hyperparameters
max_seq_length = 2048
dtype = None # Auto detection
load_in_4bit = True # 4bit QLoRA for Colab T4 16GB VRAM

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Meta-Llama-3.1-8B-Instruct",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

# 3. Configure QLoRA Adapters
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# 4. Load Dataset from Google Drive
dataset = load_dataset("json", data_files="/content/drive/MyDrive/plutus_finetune_dataset.jsonl", split="train")

def format_prompts(examples):
    texts = []
    for messages in examples["messages"]:
        text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
        texts.append(text)
    return {"text": texts}

dataset = dataset.map(format_prompts, batched=True)

# 5. Train with SFTTrainer
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "/content/drive/MyDrive/plutus_outputs",
    ),
)

trainer_stats = trainer.train()

# 6. Save LoRA Adapter to Drive
model.save_pretrained("/content/drive/MyDrive/plutus_lora_model")
tokenizer.save_pretrained("/content/drive/MyDrive/plutus_lora_model")

# 7. Merge to GGUF format for Ollama local inference
model.save_pretrained_gguf("/content/drive/MyDrive/plutus_gguf", tokenizer, quantization_method = "q4_k_m")
print("GGUF Export Complete!")
"""

OLLAMA_MODELFILE = """
# Modelfile for importing fine-tuned Plutus into Ollama locally
FROM ./plutus-q4_k_m.gguf

TEMPLATE \"\"\"{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>\"\"\"

SYSTEM \"\"\"You are Plutus, an advanced AI Trading Research Assistant. Your principle is decision-support with transparent reasoning, NOT signal generation. Always output JSON conforming to the Section 5 schema.\"\"\"

PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|eot_id|>"
PARAMETER temperature 0.2
"""


def write_colab_script_files():
    out_dir = Path(__file__).parent
    colab_file = out_dir / "colab_unsloth_training.py"
    modelfile_path = out_dir / "Modelfile"

    with open(modelfile_path, "w", encoding="utf-8") as f:
        f.write(OLLAMA_MODELFILE.strip())

    print(f"Colab fine-tuning pipeline prepared at {colab_file}")
    print(f"Ollama Modelfile saved at {modelfile_path}")


if __name__ == "__main__":
    write_colab_script_files()
